---
jobs:
  include:
    - env: [ ACTION=default, PYTHONPATH=_install/lib/python2.7/site-packages/ ]
      language: python
      install: true
      script:
        - mkdir -p "$PYTHONPATH"
        - python setup.py install --prefix=_install
        - git clean -xfd
    - env: [ ACTION=omnilint ]
      language: generic
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
